"""
🌐 Multiplayer Netcode Scaffolds
═══════════════════════════════════════════════════════════════════════
Produces ready-to-paste boilerplate for adding multiplayer to a Zerax
game. Targets the most popular stacks:
  • Colyseus     (Node.js/TS, room-based, used by Polygon.io, Sandbox)
  • Socket.IO    (Node.js, broad ecosystem, good for chat/realtime)
  • Photon Quantum (Unity, deterministic, used by AAA titles) — guide only

Endpoint: POST /api/games/multiplayer-scaffold
Body: { "stack": "colyseus" | "socketio" | "photon",
         "max_players": 8,
         "game_type": "2d-platformer" | "moba" | "battle-royale" | "co-op" }
"""
from __future__ import annotations
from typing import Dict


def colyseus_room(max_players: int, game_type: str) -> Dict[str, str]:
    return {
        "GameRoom.ts": f"""
// Colyseus room — generated by Zerax
import {{ Room, Client }} from "@colyseus/core";
import {{ Schema, type, MapSchema }} from "@colyseus/schema";

class Player extends Schema {{
  @type("number") x: number = 0;
  @type("number") y: number = 0;
  @type("string") name: string = "";
  @type("number") hp: number = 100;
}}

class State extends Schema {{
  @type({{ map: Player }}) players = new MapSchema<Player>();
  @type("number") tick: number = 0;
}}

export class GameRoom extends Room<State> {{
  maxClients = {max_players};

  onCreate() {{
    this.setState(new State());
    this.setSimulationInterval((dt) => this.update(dt), 1000 / 30); // 30 Hz tick

    this.onMessage("move", (client, data) => {{
      const p = this.state.players.get(client.sessionId);
      if (!p) return;
      p.x = data.x; p.y = data.y;
    }});

    this.onMessage("attack", (client, data) => {{
      const target = this.state.players.get(data.target);
      if (target) target.hp -= 10;
    }});
  }}

  update(dt: number) {{
    this.state.tick++;
    // game logic per tick — physics, AI, win conditions
  }}

  onJoin(client: Client, options: any) {{
    const p = new Player();
    p.name = options?.name ?? `player_${{client.sessionId.slice(0,4)}}`;
    this.state.players.set(client.sessionId, p);
  }}

  onLeave(client: Client) {{
    this.state.players.delete(client.sessionId);
  }}
}}
""",
        "server.ts": f"""
import {{ Server }} from "@colyseus/core";
import {{ WebSocketTransport }} from "@colyseus/ws-transport";
import {{ createServer }} from "http";
import express from "express";
import {{ GameRoom }} from "./GameRoom";

const app = express();
const port = Number(process.env.PORT) || 2567;

const gameServer = new Server({{
  transport: new WebSocketTransport({{ server: createServer(app) }}),
}});

gameServer.define("game", GameRoom);
gameServer.listen(port);
console.log(`✅ Colyseus listening on :${{port}}`);
""",
        "client-snippet.ts": """
// Client side (browser / React)
import { Client } from "colyseus.js";
const client = new Client("ws://localhost:2567");
const room = await client.joinOrCreate("game", { name: "ahmed" });
room.send("move", { x: 10, y: 20 });
room.state.players.onAdd = (player, id) => {
  console.log(`${id} joined as ${player.name}`);
};
""",
        "package.json": """{
  "name": "zerax-multiplayer-server",
  "version": "1.0.0",
  "scripts": { "start": "ts-node server.ts", "dev": "ts-node-dev server.ts" },
  "dependencies": {
    "@colyseus/core": "^0.16.0",
    "@colyseus/schema": "^3.0.0",
    "@colyseus/ws-transport": "^0.16.0",
    "express": "^4.19.0"
  },
  "devDependencies": {
    "ts-node": "^10.9.2",
    "ts-node-dev": "^2.0.0",
    "typescript": "^5.4.0"
  }
}""",
        "README.md": f"""# Zerax Multiplayer (Colyseus)

Generated for `{game_type}` · max {max_players} players · 30 Hz tick.

## Run
```
yarn install
yarn dev
```
Server listens on `ws://localhost:2567/game`.

## Deploy
- **Railway**: `railway up` from this folder.
- **Fly.io**: `fly launch` — Colyseus has built-in support.
- For prod: enable `presence: new RedisPresence(...)` to scale across pods.
""",
    }


def socketio_room(max_players: int, game_type: str) -> Dict[str, str]:
    return {
        "server.js": f"""
// Socket.IO realtime server — generated by Zerax
const {{ Server }} = require("socket.io");
const http = require("http");
const httpServer = http.createServer();
const io = new Server(httpServer, {{ cors: {{ origin: "*" }} }});

const MAX = {max_players};
const players = new Map();

io.on("connection", socket => {{
  if (players.size >= MAX) {{ socket.emit("room_full"); socket.disconnect(); return; }}
  players.set(socket.id, {{ x: 0, y: 0, hp: 100, name: socket.handshake.query.name }});
  io.emit("player_joined", {{ id: socket.id, ...players.get(socket.id) }});

  socket.on("move", data => {{
    const p = players.get(socket.id); if (!p) return;
    p.x = data.x; p.y = data.y;
    socket.broadcast.emit("player_moved", {{ id: socket.id, x: p.x, y: p.y }});
  }});

  socket.on("attack", data => {{
    const target = players.get(data.target);
    if (target) {{ target.hp -= 10; io.emit("hp_update", {{ id: data.target, hp: target.hp }}); }}
  }});

  socket.on("disconnect", () => {{
    players.delete(socket.id);
    io.emit("player_left", socket.id);
  }});
}});

httpServer.listen(2567);
console.log("✅ socket.io on :2567");
""",
        "client.html": """
<script src="https://cdn.socket.io/4.7.5/socket.io.min.js"></script>
<script>
const socket = io("ws://localhost:2567", { query: { name: "ahmed" } });
socket.on("player_joined", p => console.log("joined", p));
socket.on("player_moved", p => console.log("moved", p));
socket.emit("move", { x: 5, y: 10 });
</script>
""",
        "package.json": """{
  "name": "zerax-socketio",
  "scripts": { "start": "node server.js" },
  "dependencies": { "socket.io": "^4.7.5" }
}""",
        "README.md": f"""# Zerax Multiplayer (Socket.IO)
Game type: `{game_type}` · max {max_players} players.
Run: `yarn && yarn start` then open `client.html`.
""",
    }


def photon_quantum_guide(max_players: int, game_type: str) -> Dict[str, str]:
    return {
        "README.md": f"""# Photon Quantum (Unity) — Zerax setup guide

Photon Quantum is a Unity-native deterministic netcode used by AAA titles
(Stumble Guys, etc). It's not auto-generatable from code, but here's the
minimal setup for a `{game_type}` with {max_players} max players:

1. Install via Unity Package Manager:
   `https://dashboard.photonengine.com → Quantum → SDK`
2. Configure `PhotonServerSettings.asset`:
   - Region: `EU` (or your closest)
   - AppId: from Photon dashboard
3. Open `Quantum > Tools > QuantumConfig` and set:
   - `MaxPlayers = {max_players}`
   - `SimulationRate = 60`
4. Add a `GameSession` ScriptableObject and assign it to the QuantumRunner.
5. Implement systems: `MovementSystem`, `CombatSystem`, `SpawnSystem`.

For ZERAX_VOICE_CHAT integration: Photon Voice works in parallel —
add `PhotonVoiceSetup` prefab to your scene.

Need a starter template? Email support@zerax.app — we ship a Unity
package on request.
""",
    }


def generate_scaffold(stack: str, max_players: int = 8, game_type: str = "co-op") -> Dict[str, Dict[str, str]]:
    stack = (stack or "").lower()
    if stack == "colyseus":
        return {"stack": "colyseus", "files": colyseus_room(max_players, game_type)}
    if stack == "socketio":
        return {"stack": "socketio", "files": socketio_room(max_players, game_type)}
    if stack == "photon":
        return {"stack": "photon", "files": photon_quantum_guide(max_players, game_type)}
    raise ValueError(f"Unknown stack: {stack}. Choose colyseus | socketio | photon")
