"""
🚀 Hetzner Cloud Provisioning — One-Click VPS for the $799 Tier
═════════════════════════════════════════════════════════════════════

When a customer with the Full Independence tier wants their site
running on their OWN server (instead of zenrex.ai infrastructure),
they paste their Hetzner Cloud API token and click "🚀 انشر على VPS".

Flow:
  1. We validate the token by listing the account's projects.
  2. We create a CX22 server (€4.5/mo, 2 vCPU, 4 GB RAM) in `nbg1`.
  3. The server boots with a cloud-init `user_data` that:
       a. Installs Docker.
       b. Downloads the Independence Kit ZIP from our one-shot URL.
       c. Unzips it to /opt/app/.
       d. Runs `./deploy.sh <domain>` (Caddy auto-HTTPS if domain set).
  4. We persist {server_id, ip, status} on the project and poll until
     the cloud-init finishes. Status: `provisioning → ready` (~3 min).

This module is INTENTIONALLY pure — it only knows how to call Hetzner.
The orchestration (token storage, kit URL signing, status polling) is
done from `freebuild_chat.py` endpoints to keep this thin and testable.
"""
from __future__ import annotations

import logging
from typing import Any, Dict, Optional

_logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────
# Cloud-init user_data — boots the server, installs Docker, deploys kit
# ─────────────────────────────────────────────────────────────────────

_CLOUD_INIT_TEMPLATE = """#cloud-config
# Generated by Zenrex Independence — bootstraps a fresh VPS and deploys
# the customer's site from a one-time download URL.
hostname: {hostname}
timezone: Asia/Riyadh
package_update: true
package_upgrade: false

packages:
  - curl
  - unzip
  - ca-certificates

write_files:
  - path: /opt/app/.bootstrap_meta
    permissions: '0644'
    content: |
      project_id={project_id}
      domain={domain}
      kit_url={kit_url}

runcmd:
  # 1. Install Docker (idempotent)
  - bash -lc 'curl -fsSL https://get.docker.com | sh && systemctl enable --now docker'

  # 2. Fetch + extract Independence Kit
  - mkdir -p /opt/app
  - bash -lc "cd /opt/app && curl -fsSL -o kit.zip '{kit_url}' && unzip -o kit.zip && rm -f kit.zip"
  - chmod +x /opt/app/deploy.sh

  # 3. Deploy (Caddy handles HTTPS automatically if domain is set)
  - bash -lc 'cd /opt/app && DOMAIN_ARG="{domain}" && ./deploy.sh "$DOMAIN_ARG" 2>&1 | tee /var/log/zenrex-deploy.log'

  # 4. Mark done
  - bash -lc 'echo "ready" > /opt/app/.zenrex_status'

final_message: "Zenrex Independence deploy complete. Visit your domain or http://$(curl -s ifconfig.me)"
"""


def validate_token(token: str) -> Dict[str, Any]:
    """Verify the API token by listing the account's locations.
    Returns {"ok": True, "locations": [...], "datacenter_count": N} on success.
    Raises ValueError on failure with a friendly Arabic message.
    """
    try:
        from hcloud import Client
        client = Client(token=token.strip())
        locations = client.locations.get_all()
        loc_names = [loc.name for loc in locations]
        return {
            "ok": True,
            "locations": loc_names,
            "default_location": "nbg1" if "nbg1" in loc_names else (loc_names[0] if loc_names else "fsn1"),
        }
    except Exception as e:  # noqa: BLE001
        msg = str(e).lower()
        if "401" in msg or "unauthor" in msg or "invalid" in msg:
            raise ValueError("التوكن غير صالح. تأكد من نسخ التوكن كاملاً من Hetzner Console → Security → API Tokens.")
        raise ValueError(f"فشل التحقق من Hetzner: {e}")


def create_server(
    token: str,
    name: str,
    project_id: str,
    kit_url: str,
    domain: Optional[str] = None,
    server_type: str = "cx22",
    image: str = "ubuntu-24.04",
    location: str = "nbg1",
) -> Dict[str, Any]:
    """Create a Hetzner CX22 server with cloud-init that auto-deploys
    the Independence Kit. Returns server metadata + the root password.
    Caller must store the password in the project doc (encrypted).
    """
    from hcloud import Client

    client = Client(token=token.strip())
    user_data = _CLOUD_INIT_TEMPLATE.format(
        hostname=name.lower().replace(" ", "-")[:30] or "zenrex-site",
        project_id=project_id,
        domain=(domain or "").strip(),
        kit_url=kit_url,
    )

    try:
        resp = client.servers.create(
            name=name[:50] or f"zenrex-{project_id[:8]}",
            server_type=server_type,
            image=image,
            location=location,
            user_data=user_data,
        )
    except Exception as e:  # noqa: BLE001
        _logger.exception("Hetzner create_server failed: %s", e)
        msg = str(e)
        if "401" in msg or "unauthorized" in msg.lower():
            raise ValueError("التوكن غير صالح أو منتهي.")
        if "quota" in msg.lower() or "limit" in msg.lower():
            raise ValueError("حساب Hetzner وصل لحد السيرفرات. ارفع الحد من الـ Console.")
        if "billing" in msg.lower() or "payment" in msg.lower():
            raise ValueError("Hetzner يطلب تأكيد بطاقة الائتمان قبل إنشاء أول سيرفر.")
        raise ValueError(f"فشل إنشاء السيرفر: {e}")

    server = resp.server
    ip = None
    try:
        if server.public_net and server.public_net.ipv4:
            ip = server.public_net.ipv4.ip
    except Exception:
        ip = None
    return {
        "ok": True,
        "server_id": str(server.id),
        "name": server.name,
        "status": server.status,
        "ip": ip,
        "ipv4": ip,
        "root_password": resp.root_password,
        "server_type": server_type,
        "image": image,
        "location": location,
    }


def get_server_status(token: str, server_id: str) -> Dict[str, Any]:
    """Poll the server status. Returns a small dict with `status` and `ip`."""
    from hcloud import Client
    client = Client(token=token.strip())
    try:
        srv = client.servers.get_by_id(int(server_id))
    except Exception as e:  # noqa: BLE001
        raise ValueError(f"فشل قراءة حالة السيرفر: {e}")
    ip = None
    try:
        if srv.public_net and srv.public_net.ipv4:
            ip = srv.public_net.ipv4.ip
    except Exception:
        ip = None
    return {
        "ok": True,
        "server_id": str(srv.id),
        "name": srv.name,
        "status": srv.status,  # initializing | running | starting | stopping | off | deleting
        "ip": ip,
    }


def delete_server(token: str, server_id: str) -> Dict[str, Any]:
    """Remove a server. Used when the customer cancels / wants to teardown."""
    from hcloud import Client
    client = Client(token=token.strip())
    try:
        srv = client.servers.get_by_id(int(server_id))
        action = client.servers.delete(srv)
        return {"ok": True, "action_id": getattr(action, "id", None)}
    except Exception as e:  # noqa: BLE001
        raise ValueError(f"فشل حذف السيرفر: {e}")
