"""
💎 Independence Kit — Premium Delivery Bundle for the $799 Tier
═════════════════════════════════════════════════════════════════════

When a customer buys the "Full Independence" tier, they receive much
more than the raw HTML. This module produces an enterprise-grade
delivery kit that includes:

  • Dockerfile + docker-compose.yml (production-ready)
  • nginx.conf (with TLS hints + gzip + caching)
  • deploy.sh (idempotent bash deploy script)
  • README.md (project-specific quickstart)
  • ARCHITECTURE.md (5+ pages, Claude-generated)
  • SECRETS.template.env (placeholders, never real values)
  • .gitignore + LICENSE (MIT default)
  • HANDOVER.md (formal delivery letter + 60-day support terms)

The ARCHITECTURE.md is generated per-project via Claude based on
the project HTML/blueprint/discovery answers — so every delivery
kit is bespoke, not boilerplate.

Public API:
  build_independence_kit(project: dict) -> Dict[str, str]
      Returns a dict of {filename: file_contents} that the export
      endpoint zips and streams to the customer.
"""
from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional

from modules.shared.claude_simple import ask_claude

_logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────
# Static templates — boring, well-tested infra config
# ─────────────────────────────────────────────────────────────────────

_DOCKERFILE_NGINX = """# Production Dockerfile — multi-stage static site
# Generated by Zenrex Independence Kit for project: {project_name}
# Build: docker build -t {slug}:latest .
# Run:   docker run -p 80:80 {slug}:latest
FROM nginx:1.27-alpine
LABEL maintainer="{owner_email}"
LABEL project="{project_name}"
LABEL delivered_by="Zenrex.ai · Independence Tier"

# Drop the default config and copy ours
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copy the production assets
COPY index.html /usr/share/nginx/html/index.html
COPY assets/ /usr/share/nginx/html/assets/

# Healthcheck — fail fast if nginx is dead
HEALTHCHECK --interval=30s --timeout=3s --retries=3 \\
  CMD wget -qO- http://127.0.0.1/ >/dev/null 2>&1 || exit 1

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
"""

_DOCKER_COMPOSE = """# docker-compose.yml — single-host production setup
# Generated by Zenrex Independence Kit for project: {project_name}
# Usage:
#   1. Copy .env from SECRETS.template.env and fill values
#   2. docker compose up -d
#   3. Optionally add a Caddy/Traefik reverse proxy for auto-TLS
version: "3.9"
services:
  web:
    build: .
    image: {slug}:latest
    container_name: {slug}_web
    restart: unless-stopped
    ports:
      - "${{HOST_HTTP_PORT:-80}}:80"
    environment:
      - TZ=${{TZ:-Asia/Riyadh}}
    networks:
      - {slug}_net
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1/"]
      interval: 30s
      timeout: 3s
      retries: 3

networks:
  {slug}_net:
    driver: bridge
"""

_NGINX_CONF = """# nginx.conf — production static site
# Tuned for: gzip, cache, security headers, SPA-fallback
# Generated by Zenrex Independence Kit
server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;
    root         /usr/share/nginx/html;
    index        index.html;

    # Security
    add_header X-Frame-Options              "SAMEORIGIN"            always;
    add_header X-Content-Type-Options       "nosniff"               always;
    add_header Referrer-Policy              "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy           "camera=(), microphone=(), geolocation=()" always;

    # Gzip
    gzip on;
    gzip_vary on;
    gzip_min_length 1024;
    gzip_proxied any;
    gzip_types
        text/plain text/css text/xml text/javascript
        application/json application/javascript application/xml+rss
        application/atom+xml image/svg+xml;

    # Cache hashed assets for 1 year
    location ~* \\.(?:css|js|woff2?|ttf|otf|eot|svg|png|jpe?g|gif|webp|avif|ico)$ {
        expires 1y;
        access_log off;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # HTML — short cache so updates land quickly
    location ~* \\.html$ {
        expires 5m;
        add_header Cache-Control "public, must-revalidate";
    }

    # SPA fallback (safe even for non-SPA sites — only hits if file missing)
    location / {
        try_files $uri $uri/ /index.html;
    }

    error_page 404 /index.html;
}
"""

_DEPLOY_SH = """#!/usr/bin/env bash
# deploy.sh — one-shot production deploy
# Generated by Zenrex Independence Kit for project: {project_name}
#
# Usage (on your VPS, as root or sudo user):
#   chmod +x deploy.sh
#   ./deploy.sh
#
# Prerequisites:
#   • Ubuntu 22.04+ or Debian 12+
#   • A domain pointing to this server's public IP (optional but recommended)
#
set -euo pipefail

PROJECT_SLUG="{slug}"
DOMAIN="${{1:-}}"   # pass your domain as first arg, e.g. ./deploy.sh example.com

echo "🚀 Deploying $PROJECT_SLUG..."

# 1. System deps
if ! command -v docker >/dev/null 2>&1; then
  echo "📦 Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  systemctl enable --now docker
fi

# 2. Build & run
echo "🔨 Building image..."
docker compose build
echo "▶️  Starting container..."
docker compose up -d

# 3. Optional: install Caddy for auto-TLS (only if domain provided)
if [[ -n "$DOMAIN" ]]; then
  echo "🔐 Installing Caddy for HTTPS on $DOMAIN..."
  apt-get update -y
  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https curl
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | tee /etc/apt/sources.list.d/caddy-stable.list >/dev/null
  apt-get update -y
  apt-get install -y caddy

  cat > /etc/caddy/Caddyfile <<EOF
$DOMAIN {{
    reverse_proxy localhost:80
    encode gzip
}}
EOF
  systemctl reload caddy
  echo "✅ HTTPS enabled. Visit https://$DOMAIN"
else
  PUBLIC_IP=$(curl -s ifconfig.me || echo "<server-ip>")
  echo "✅ Deployed. Visit http://$PUBLIC_IP"
  echo "ℹ️  Tip: re-run with a domain argument for auto-HTTPS: ./deploy.sh yourdomain.com"
fi
"""

_GITIGNORE = """# Generated by Zenrex Independence Kit
node_modules/
dist/
build/
.env
.env.local
.env.production
*.log
.DS_Store
Thumbs.db
.vscode/
.idea/
__pycache__/
*.pyc
"""

_LICENSE_MIT = """MIT License

Copyright (c) {year} {owner_name}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
"""

_SECRETS_TEMPLATE = """# SECRETS.template.env — copy to `.env` on your server and fill in REAL values
# DO NOT commit .env to git. Already added to .gitignore.
# Generated by Zenrex Independence Kit for {project_name}

# ─── Host configuration ──────────────────────────────────────────────
TZ=Asia/Riyadh
HOST_HTTP_PORT=80

# ─── Domain & TLS (managed by Caddy, no manual cert needed) ──────────
DOMAIN=
ADMIN_EMAIL=

# ─── Future expansion — add these as you grow ────────────────────────
# DATABASE_URL=postgresql://user:pass@host:5432/dbname
# STRIPE_SECRET_KEY=sk_live_XXXX
# STRIPE_WEBHOOK_SECRET=whsec_XXXX
# SENDGRID_API_KEY=SG.XXXX
# CLOUDFLARE_API_TOKEN=XXXX
"""


# ─────────────────────────────────────────────────────────────────────
# Architecture documentation — generated bespoke per project via Claude
# ─────────────────────────────────────────────────────────────────────

_ARCHITECTURE_SYSTEM_PROMPT = """أنت كاتب توثيق تقني محترف يكتب وثائق Architecture مفصلة لمشاريع تم تسليمها كاملةً لعملاء.

**المهمة:** أعطيك ملخّص مشروع ويب (HTML ستاتيك) + ميتاداتا. اكتب ملف ARCHITECTURE.md متكامل بـ Markdown يفسّر:

1. **نظرة عامة** — وش الموقع، الجمهور المستهدف، القيمة الرئيسية.
2. **بنية الملفات** — شجرة الملفات + شرح كل ملف.
3. **التقنيات المستخدمة** — HTML5/CSS3/JS vanilla أو frameworks، لو موجودة.
4. **التصميم البصري** — اللون السائد، Typography، Layout strategy.
5. **التفاعلات الديناميكية** — أي JavaScript، Animations، Forms.
6. **استراتيجية الـ Performance** — gzip، caching، lazy loading.
7. **استراتيجية الـ SEO** — meta tags، semantic HTML، Open Graph.
8. **خطوات التطوير المستقبلية** — كيف يضيف backend، DB، Auth لاحقاً.
9. **نموذج DNS وSSL** — Caddy تلقائي عبر Let's Encrypt.
10. **Troubleshooting شائع** — أخطاء متوقعة وحلولها.

**القواعد:**
- اللغة: عربي فصيح مهني (مو لهجة).
- الطول: 5+ صفحات (≈2500 كلمة).
- لا تخترع ميزات غير موجودة في الـ HTML.
- استخدم headings (##, ###) وlists وcode blocks.
- اختم بـ "تم تسليم هذا المشروع رسمياً بواسطة Zenrex.ai — تاريخ التسليم: {today}."
"""


def _slugify(name: str) -> str:
    """Make a safe Docker/file slug from a project name."""
    import re
    s = (name or "zenrex-project").strip().lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    s = re.sub(r"-+", "-", s).strip("-")
    return s or "zenrex-project"


def _generate_readme(project: Dict[str, Any], slug: str, today: str) -> str:
    name = project.get("name") or "Zenrex Project"
    desc = project.get("description") or "موقع تم بناؤه عبر Zenrex.ai"
    return f"""# {name}

> {desc}

**نُشر هذا المشروع بشكل مستقل خارج Zenrex.ai في تاريخ {today}.**
أنت الآن المالك الكامل للكود — Zenrex لم يعد له أي وصول أو ارتباط بهذا المشروع.

---

## 🚀 نشر سريع (3 أوامر فقط)

على أي سيرفر Ubuntu 22.04+ أو Debian 12+:

```bash
# 1. اسحب الكود من GitHub (أو فك ZIP)
git clone https://github.com/YOU/{slug}.git && cd {slug}

# 2. اعطِ صلاحية تنفيذ لـ deploy.sh
chmod +x deploy.sh

# 3. شغّل النشر (بدّل example.com بدومينك أو احذفه للنشر على IP فقط)
./deploy.sh example.com
```

في خلال 3-5 دقائق راح يكون موقعك live على HTTPS.

---

## 📂 محتوى الـ ZIP

```
{slug}/
├── index.html                ← الموقع نفسه
├── assets/                   ← الصور والـ media
├── Dockerfile                ← بناء صورة Production
├── docker-compose.yml        ← تشغيل بكبسة زر
├── nginx.conf                ← تهيئة nginx (gzip + cache + security headers)
├── deploy.sh                 ← سكربت نشر تلقائي (Docker + Caddy للـ HTTPS)
├── SECRETS.template.env      ← قالب متغيرات البيئة
├── ARCHITECTURE.md           ← توثيق تقني كامل
├── HANDOVER.md               ← خطاب التسليم الرسمي + شروط الدعم
├── LICENSE                   ← رخصة MIT
├── .gitignore
└── README.md                 ← هذا الملف
```

---

## 🔧 تطوير لاحق

- **تعديل التصميم**: عدّل `index.html` و`assets/` مباشرة.
- **إضافة Backend**: أضف خدمة `api` في `docker-compose.yml` (مثلاً FastAPI أو Node.js).
- **إضافة DB**: أضف خدمة `postgres` في نفس الـ compose.
- **مراقبة**: أضف Uptime Kuma أو Grafana للـ stack.

اطّلع على `ARCHITECTURE.md` لتفاصيل عميقة عن كل شيء.

---

## 📞 الدعم (60 يوم)

عميل Zenrex Independence Tier ($799) يحصل على:
- 60 يوم دعم تقني عبر البريد: **support@zenrex.ai**
- ضمان "البناء يشتغل" — لو فيه bug في الكود اللي سُلّم، نصلحه مجاناً.
- لا يشمل: تطوير ميزات جديدة، تكامل APIs جديدة، نقل لـ stack ثاني.

بعد 60 يوم، تقدر تتعاقد مع أي مبرمج (المشروع كله ملكك ومفتوح).

---

تم التسليم بتاريخ: **{today}** · مشروع: `{slug}` · إصدار Kit: v1.0
"""


def _generate_handover(project: Dict[str, Any], slug: str, today: str, owner_email: str) -> str:
    name = project.get("name") or "Zenrex Project"
    pid = project.get("id") or "—"
    return f"""# 📜 خطاب تسليم رسمي — Zenrex Independence Tier

**التاريخ**: {today}
**رقم المشروع**: `{pid}`
**اسم المشروع**: {name}
**العميل**: {owner_email}
**الباقة**: Full Independence — $799

---

## ١. ما تم تسليمه

نُقرّ نحن، Zenrex.ai، بأننا سلّمنا للعميل المذكور أعلاه ما يلي:

- ✅ كامل ملفات Frontend (HTML/CSS/JS/Assets) — حقوق ملكية كاملة.
- ✅ Delivery Kit إنتاجي (Dockerfile + nginx.conf + deploy.sh + docker-compose).
- ✅ توثيق تقني (ARCHITECTURE.md ≈5 صفحات).
- ✅ رخصة MIT — العميل يقدر يعدّل/يبيع/يدمج بدون قيود.
- ✅ قالب متغيرات بيئة (SECRETS.template.env).
- ✅ إرشاد لنقل ملكية مستودع GitHub لاسم العميل.
- ✅ إرشاد لنشر VPS مستقل (Hetzner / DigitalOcean / AWS Lightsail).

---

## ٢. التزامات Zenrex بعد التسليم

- **دعم 60 يوم** عبر `support@zenrex.ai` — يشمل إصلاح أخطاء في الكود المُسلّم فقط.
- **لا يشمل**: تطوير ميزات جديدة، دعم infrastructure، نقل لتقنيات ثانية.
- **بعد 60 يوم**: لا توجد التزامات. المشروع ملك العميل بالكامل.

---

## ٣. ما لا يشمله التسليم

⚠️ هذا التسليم **لا يشمل**:

- استضافة على سيرفرات Zenrex — العميل مسؤول عن استضافة مشروعه على VPS خاص به.
- شراء دومين — العميل يشتري دومينه بنفسه (Namecheap / Cloudflare / GoDaddy).
- إدارة DNS — يتم شرح خطوات الإعداد لكن العميل ينفّذها بنفسه.
- مفاتيح APIs لخدمات خارجية — أي Stripe/SendGrid/إلخ، العميل يفتحها بحسابه.

---

## ٤. حقوق الملكية الفكرية

بمجرد إكمال الدفع، **جميع حقوق الملكية الفكرية للكود المُسلّم تنتقل للعميل**.
لا يحتفظ Zenrex.ai بأي حق في:
- إعادة استخدام التصميم لعملاء آخرين.
- الادعاء بملكية الكود.
- استرجاع أي جزء من المُسلّم.

---

## ٥. توقيع رسمي

| الطرف | الاسم | التاريخ |
|---|---|---|
| المُسلِّم | Zenrex.ai (نظام آلي) | {today} |
| المُستلِم | {owner_email} | {today} |

> هذه الوثيقة وُلّدت تلقائياً من نظام Zenrex Independence Kit v1.0
> رقم الإصدار: `{pid[:8]}-{today.replace('-', '')}`
"""


async def _generate_architecture_md(project: Dict[str, Any], today: str) -> str:
    """Call Claude to generate a bespoke ARCHITECTURE.md for this project."""
    html = project.get("current_html") or ""
    # Truncate to fit comfortably in Claude's context
    html_preview = html[:8000] if len(html) > 8000 else html
    discovery = (project.get("workflow_state") or {}).get("discovery") or {}
    blueprint = discovery.get("blueprint") or {}
    name = project.get("name") or "Zenrex Project"
    desc = project.get("description") or ""

    user_msg = json.dumps({
        "name": name,
        "description": desc,
        "vertical": blueprint.get("vertical"),
        "vertical_name_ar": blueprint.get("vertical_name_ar"),
        "phases": blueprint.get("phases", [])[:10],
        "essentials": blueprint.get("essentials", [])[:15],
        "html_preview_first_8k_chars": html_preview,
        "html_size_bytes": len(html),
        "today": today,
    }, ensure_ascii=False)

    sys_prompt = _ARCHITECTURE_SYSTEM_PROMPT.format(today=today)
    try:
        text = await ask_claude(
            system=sys_prompt,
            user_message=user_msg,
            max_tokens=4096,
            timeout=110.0,
        )
        return (text or "").strip() or _fallback_architecture(name, today)
    except Exception as e:  # noqa: BLE001
        _logger.warning(
            "architecture_md generation failed (%s: %s) — using fallback",
            type(e).__name__, str(e) or "<empty>",
        )
        return _fallback_architecture(name, today)


def _fallback_architecture(name: str, today: str) -> str:
    return f"""# ARCHITECTURE — {name}

> هذا الملف تم توليده بنسخة احتياطية بسبب تعذّر الاتصال بـ Claude.
> راجع `README.md` للاطلاع على ملخص التشغيل، ثم تواصل مع `support@zenrex.ai`.

## 1. نظرة عامة
موقع HTML/CSS/JS ستاتيك مُولّد بواسطة Zenrex.ai Builder. الموقع self-contained وقابل للنشر على أي خادم Nginx/Apache.

## 2. التقنيات
- HTML5 + CSS3 + Vanilla JavaScript
- Nginx 1.27 (alpine) كـ web server
- Docker + Docker Compose للنشر
- Caddy للـ HTTPS التلقائي (اختياري)

## 3. النشر
راجع `deploy.sh` و`README.md`.

## 4. الـ Performance
gzip مفعّل + caching headers لمدة سنة لكل الـ assets + cache قصير للـ HTML.

## 5. الأمن
- X-Frame-Options: SAMEORIGIN
- X-Content-Type-Options: nosniff
- Referrer-Policy: strict-origin-when-cross-origin
- Permissions-Policy: camera/microphone/geolocation disabled

---
تم تسليم هذا المشروع رسمياً بواسطة Zenrex.ai — تاريخ التسليم: {today}.
"""


async def build_independence_kit(project: Dict[str, Any], owner_email: str = "—") -> Dict[str, str]:
    """
    Build the full Independence Tier delivery bundle for a project.
    Returns a dict {filename: text_content} that the export endpoint
    will zip alongside the HTML + assets.
    """
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    year = datetime.now(timezone.utc).year
    slug = _slugify(project.get("name") or "zenrex-project")
    name = project.get("name") or "Zenrex Project"

    # Architecture doc — async Claude call
    arch_md = await _generate_architecture_md(project, today)

    return {
        "README.md": _generate_readme(project, slug, today),
        "ARCHITECTURE.md": arch_md,
        "HANDOVER.md": _generate_handover(project, slug, today, owner_email),
        "Dockerfile": _DOCKERFILE_NGINX.format(
            project_name=name, slug=slug, owner_email=owner_email
        ),
        "docker-compose.yml": _DOCKER_COMPOSE.format(project_name=name, slug=slug),
        "nginx.conf": _NGINX_CONF,
        "deploy.sh": _DEPLOY_SH.format(project_name=name, slug=slug),
        "SECRETS.template.env": _SECRETS_TEMPLATE.format(project_name=name),
        ".gitignore": _GITIGNORE,
        "LICENSE": _LICENSE_MIT.format(year=year, owner_name=owner_email),
    }
